import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import Navbar from "./components/Navbar";

 
const inter = Roboto({ weight: '300',
subsets: ['latin'],});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
      {children}</body>
    </html>
    </ClerkProvider>
  );
}
